### ISSUE TITLE
Put code on `lib` folder

### ISSUE THREAD

**Issue by piranna** [luii/nogit#2]
Put all code except `nogit.js` in a `lib` folder so it gets cleaner. Currently `nogit.js` is heavily isolated, so it should not be difficult to add tests later :-) Good job! :-D

**Comment by luii** [comment]
I've put most of the code into `lib/index.js`.
I think testing the binaries is useless, because they dont contain complex logic - only the high level function call.
But im writing tests for the `lib/index.js` file

**Comment by piranna** [comment]
Cool, that's the way to go.

**Comment by luii** [comment]
Since all the logic is now located inside the `lib` folder i'll close this Issue
