### ISSUE TITLE
npm module with same name

### ISSUE THREAD

**Issue by thisconnect** [luii/nogit#5]
https://www.npmjs.com/package/nogit

just that you are aware there is already a nogit on npm.

**Comment by luii** [comment]
no i wasnt aware of this thanks , i think this gets published with a nodeos prefix

**Comment by piranna** [comment]
Doesn't have it the same purposse that `nogit`? Yes, we can publish it as `nodeos-git`, but maybe it would be interesting to join efforts or something...

**Comment by luii** [comment]
we published it as `nodeos-git` so we can close it.
